matrix:
  include:
    - language: python
      python:
        - '3.6'
      install:
        - pip install -r requirements.txt
      script: python script/make_html.py
    - language: node_js
      node_js:
        - 10.16.0
      before_install:
        - cd hg-app
      install:
        - npm install
      script:
        - npm build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master