language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
script: python script/make_html.py
after_success:
  - git add .
  - git commit -m'add blogs'
  - git push
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master