branches:
  only:
  - master
language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
script: python script/make_html.py
after_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'